<a href="https://colab.research.google.com/github/Venkatesh0406/python/blob/main/ad_day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
a = np.random.randint(20,50,15)

In [9]:
a

array([42, 31, 40, 43, 43, 31, 34, 46, 24, 29, 39, 28, 46, 29, 45])

In [10]:
a.ndim

1

In [11]:
a[12]

46

In [12]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [13]:
b[3] #row

array([46, 45, 52, 74, 65, 53, 60, 55])

In [14]:
b[5,5]

67

In [15]:
b[:,6] #column

array([61, 48, 68, 60, 75, 67, 52])

In [16]:
b[5:4]

array([], shape=(0, 8), dtype=int64)

In [17]:
b[3:4]

array([[46, 45, 52, 74, 65, 53, 60, 55]])

In [18]:
b[3:6]

array([[46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [19]:
b[3:6,1:3]

array([[45, 52],
       [72, 46],
       [67, 53]])

In [ ]:
array [ row start : row-end : row-step , col_start : col_end : col_step]

In [21]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [22]:
b[3,6] # 1 st row and 3 column position

60

In [25]:
b[1:7,1:7]

array([[59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60],
       [72, 46, 69, 65, 75, 75],
       [67, 53, 77, 60, 67, 67],
       [54, 74, 69, 54, 64, 52]])

In [27]:
b[-3:-1]

array([[64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [28]:
b[-6:-1]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [38]:
b[2,1]

56

In [39]:
np.where(b>30)

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
        2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
        5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5,
        6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3,
        4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7]))